name: build
on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: src/github.com/fishworks/gofish

    - name: set up go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: set GOPATH
      # temporary fix for https://github.com/actions/setup-go/issues/12
      run: |
        echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
        echo "##[add-path]$GITHUB_WORKSPACE/bin"
        mkdir bin

    - name: run style tests
      working-directory: src/github.com/fishworks/gofish
      run: make test-lint

    - name: run unit tests
      working-directory: src/github.com/fishworks/gofish
      run: make test-unit

    - name: build
      working-directory: src/github.com/fishworks/gofish
      run: |
        go get -u github.com/mitchellh/gox
        make build-cross
        make dist checksum

    - name: upload tarballs to azure
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: src/github.com/fishworks/gofish/_dist/
        container_name: '$web'
        connection_string: ${{ secrets.ConnectionString }}
        extra_args: '--pattern "*.tar*" --destination-path "releases"'

    - name: upload zip files to azure
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: src/github.com/fishworks/gofish/_dist/
        container_name: '$web'
        connection_string: ${{ secrets.ConnectionString }}
        extra_args: '--pattern "*.zip*" --destination-path "releases"'
