name: test
on: pull_request
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: build
      run: make
    - name: run style tests
      run: make test-lint
    - name: run unit tests
      run: make test-unit
