name: Build and Deploy to Azure

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: src/github.com/fishworks/gofish

    - name: set up go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: set GOPATH
      # temporary fix for https://github.com/actions/setup-go/issues/12
      run: |
        echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
        echo "##[add-path]$GITHUB_WORKSPACE/bin"
        mkdir bin

    - name: install dependencies
      working-directory: src/github.com/fishworks/gofish
      run: |
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure

    - name: build
      working-directory: src/github.com/fishworks/gofish
      run: make dist checksum

    - name: upload to azure
      working-directory: src/github.com/fishworks/gofish
      uses: bacongobbler/azure-blob-storage-upload@master
      with:
        source-dir: ./_dist
        connection-string: ${{ secrets.ConnectionString }}
        extra-args: "--pattern [*.tar.gz*, *.zip*]"
