name: Build and Deploy to Azure

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: set up go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: set GOPATH
      # temporary fix for https://github.com/actions/setup-go/issues/12
      run: |
        mkdir $GITHUB_WORKSPACE/bin
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"

    - name: install dependencies
      run: |
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure

    - name: build
      run: make dist checksum

    - name: upload to azure
      uses: bacongobbler/azure-blob-storage-upload@master
      with:
        source-dir: ./_dist
        connection-string: ${{ secrets.ConnectionString }}
        extra-args: "--pattern [*.tar.gz*, *.zip*]"
